const actionTypes = {
    FORM_SUBMIT_START: "FORM_SUBMIT_START",
    FORM_SUBMIT_SUCCESS: "FORM_SUBMIT_SUCCESS",
    FORM_SUBMIT_FAILED: "FORM_SUBMIT_FAILED",
    LOGOUT_START:"LOGOUT_START",
}

export default actionTypes;